### ISSUE TITLE
Remove package from Atmosphere

### ISSUE THREAD

**Issue by splendido** [halilertekin/meteor-materialize#2]

**Comment by splendido** [comment]
Ok, I've flagged it ;-)

**Comment by dandv** [comment]
@halilertekin, not sure if @splendido explained _why_ he'd like you to remove the package from Atmosphere, but the reason is simple: we already have an [official integration from the Materialize guys themselves](https://github.com/Dogfalo/materialize/blob/master/package.js).

Please help us keep Atmosphere clean by hiding your package from Atmosphere. It will still be installable by your apps, just hidden from new searches. All you need to do is run

```
meteor admin set-unmigrated halil:materialize
```

Thanks!

**Comment by splendido** [comment]
...the explanation for the request was there when I opened this issue!

Lets make a screenshot before your one disappears too ;-)

**Comment by dandv** [comment]
Hey @tmeasday, how about moderator super-powers to unmigrate flagged packages? Some folks might call it quits with GitHub or get hit but a bus or whatnot, and can't unmigrate their stuff even if they wanted to (I'm sure @halilertekin wants to help keep Atmosphere clean, right @halilertekin?)

**Comment by splendido** [comment]
I actually flagged this one, so I guess my _MOD_ power was used in this case...
Are you still seeing this?

**Comment by halilertekin** [comment]
Some errors in this package fixed  ,Sorry , i'm new seen . Thanks @dandv @splendido ,
